[package]
name = "users"
version = "0.1.0"
edition = "2021"

[dependencies]
async-global-executor = "3.1.0"
futures = "0.3.31"
lapin = "2.5.3"
scylla = "1.1.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
